---
#Timestep for the model
sim_dt: 0.25

#Ordered instructions for how to calibrate the model
calibration:
    demographics:
      adjustables: [[acm, 0.5, 2]]
      measurables: [alive]
#    transmission_total:
#      adjustables: [[ch_pop_sus, 0.5, 10], [ad_pop_sus, 1, 10], [hvl_cal, "all", 0, 1]]
#      measurables: [prev]
#    seroconversion:
#      adjustables: [[eag_020_m, "all", 0.01, 10], [eag_020_f, "all", 0.01, 10], [eag_2040_m, "all", 0.01, 10], [eag_2040_f, "all", 0.01, 10],[eag_4060_m, "all", 0.01, 10], [eag_4060_f, "all", 0.01, 10],[eag_60_m, "all", 0.01, 10], [eag_60_f, "all", 0.01, 10]]
#      measurables: [eag_ott]
#    cirrhosis:
#      adjustables: [[sag_020_m, "all", 0.01, 10], [sag_020_f, "all", 0.01, 10], [sag_2040_m, "all", 0.01, 10], [sag_2040_f, "all", 0.01, 10],[sag_4060_m, "all", 0.01, 10], [sag_4060_f, "all", 0.01, 10],[sag_60_m, "all", 0.01, 10], [sag_60_f, "all", 0.01, 10], [cc_020_m, "all", 0.01, 10], [cc_020_f, "all", 0.01, 10], [cc_2040_m, "all", 0.01, 10], [cc_2040_f, "all", 0.01, 10],[cc_4060_m, "all", 0.01, 10], [cc_4060_f, "all", 0.01, 10],[cc_60_m, "all", 0.01, 10], [cc_60_f, "all", 0.01, 10]]
#      measurables: [cl_cir]
#    hcc:
#      adjustables: [[hcc_020_m, "all", 0.01, 10], [hcc_020_f, "all", 0.01, 10], [hcc_2040_m, "all", 0.01, 10], [hcc_2040_f, "all", 0.01, 10],[hcc_4060_m, "all", 0.01, 10], [hcc_4060_f, "all", 0.01, 10],[hcc_60_m, "all", 0.01, 10], [hcc_60_f, "all", 0.01, 10]]
#      measurables: [cl_hcc]
