---
#Timestep for the model
sim_dt: 0.25

#Ordered instructions for how to calibrate the model
calibration:
#    demographics:
#      adjustables: [[acm, 0.5, 2]]
#      measurables: [alive]
#    transmission_total:
#      adjustables: [[ch_pop_sus, 0.5, 10], [ad_pop_sus, 1, 10], [hvl_cal, "all", 0, 1]]
#      measurables: [prev]
#    seroconversion:
#      adjustables: [[eag_020_m, "all", 0.01, 10], [eag_020_f, "all", 0.01, 10], [eag_2040_m, "all", 0.01, 10], [eag_2040_f, "all", 0.01, 10],[eag_4060_m, "all", 0.01, 10], [eag_4060_f, "all", 0.01, 10],[eag_60_m, "all", 0.01, 10], [eag_60_f, "all", 0.01, 10]]
#      measurables: [eag_ott]


## 4 AGE BINS NO INITIAL CONDITIONS
#    0_20 cirrhosis:
#      adjustables: [ [sag_020_m, "all", 0.01, 10 ], [ sag_020_f, "all", 0.01, 10 ], [ cc_020_m, "all", 0.01, 10 ], [ cc_020_f, "all", 0.01, 10 ]]
#      measurables: [cl_cir]
#    0_20 hcc:
#      adjustables: [ [hcc_020_m, "all", 0.01, 10 ], [ hcc_020_f, "all", 0.01, 10]]
#      measurables: [cl_hcc]
#
#    20_40 cirrhosis:
#      adjustables: [ [ sag_2040_m, "all", 0.01, 10 ], [ sag_2040_f, "all", 0.01, 10 ], [ cc_2040_m, "all", 0.01, 10 ], [ cc_2040_f, "all", 0.01, 10 ]]
#      measurables: [ cl_cir ]
#    20_40 hcc:
#      adjustables: [ [ hcc_2040_m, "all", 0.01, 10 ], [ hcc_2040_f, "all", 0.01, 10 ]]
#      measurables: [ cl_hcc ]
#
#    40_60 cirrhosis:
#      adjustables: [ [ sag_4060_m, "all", 0.01, 10 ], [ sag_4060_f, "all", 0.01, 10 ], [ cc_4060_m, "all", 0.01, 10 ], [ cc_4060_f, "all", 0.01, 10 ]]
#      measurables: [ cl_cir ]
#    40_60 hcc:
#      adjustables: [ [ hcc_4060_m, "all", 0.01, 10 ], [ hcc_4060_f, "all", 0.01, 10 ]]
#      measurables: [ cl_hcc ]
#
#    60+ cirrhosis:
#        adjustables: [ [ sag_60_m, "all", 0.01, 10 ], [ sag_60_f, "all", 0.01, 10 ], [ cc_60_m, "all", 0.01, 10 ], [ cc_60_f, "all", 0.01, 10 ] ]
#        measurables: [ cl_cir ]
#
#    60+ hcc:
#        adjustables: [[ hcc_60_m, "all", 0.01, 10 ], [ hcc_60_f, "all", 0.01, 10 ]]
#        measurables: [ cl_hcc ]


## ALL AGE BINS WITH INITIAL CONDITIONS ADDED ACTIVE/INACTIVE
#    0_0 cirrhosis:
#      adjustables: [[ i_sdis, "0-0M", 0.01, 10 ],[ i_edis, "0-0M", 0.01, 10 ],[ i_sdis, "0-0F", 0.01, 10 ],[ i_edis, "0-0F", 0.01, 10 ],[ i_ccp, "0-0M", 0.01, 10 ],[ i_dcp, "0-0M", 0.01, 10 ], [ i_ccp, "0-0F", 0.01, 10 ],[ i_dcp, "0-0F", 0.01, 10 ], [ sag_020_m, "all", 0.01, 10 ], [ sag_020_f, "all", 0.01, 10 ], [ cc_020_m, "all", 0.01, 10 ], [ cc_020_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_cir ]
#    0_0 hcc:
#      adjustables: [ [ i_sdis, "0-0M", 0.01, 10 ],[ i_edis, "0-0M", 0.01, 10 ],[ i_sdis, "0-0F", 0.01, 10 ],[ i_edis, "0-0F", 0.01, 10 ],[ i_hcp, "0-0M", 0.01, 10 ], [ i_hcp, "0-0F", 0.01, 10 ], [hcc_020_m, "all", 0.01, 10 ], [ hcc_020_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_hcc ]
#
#    1_4 cirrhosis:
#      adjustables: [ [ i_sdis, "1-4M", 0.01, 10 ],[ i_edis, "1-4M", 0.01, 10 ],[ i_sdis, "1-4F", 0.01, 10 ],[ i_edis, "1-4F", 0.01, 10 ],[ i_ccp, "1-4M", 0.01, 10 ],[ i_ccp, "1-4F", 0.01, 10 ], [ i_dcp, "1-4M", 0.01, 10 ],[ i_dcp, "1-4F", 0.01, 10 ], [ sag_020_m, "all", 0.01, 10 ], [ sag_020_f, "all", 0.01, 10 ], [ cc_020_m, "all", 0.01, 10 ], [ cc_020_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_cir ]
#    1_4 hcc:
#      adjustables: [ [ i_sdis, "1-4M", 0.01, 10 ],[ i_edis, "1-4M", 0.01, 10 ],[ i_sdis, "1-4F", 0.01, 10 ],[ i_edis, "1-4F", 0.01, 10 ],[ i_hcp, "1-4M", 0.01, 10 ],[ i_hcp, "1-4F", 0.01, 10 ], [hcc_020_m, "all", 0.01, 10 ], [ hcc_020_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_hcc ]
#
#    5_9 cirrhosis:
#      adjustables: [[ i_sdis, "5-9M", 0.01, 10 ],[ i_edis, "5-9M", 0.01, 10 ],[ i_sdis, "5-9F", 0.01, 10 ],[ i_edis, "5-9F", 0.01, 10 ],[ i_ccp, "5-9M", 0.01, 10 ],[ i_ccp, "5-9F", 0.01, 10 ], [ i_dcp, "5-9M", 0.01, 10 ],[ i_dcp, "5-9F", 0.01, 10 ],[ sag_020_m, "all", 0.01, 10 ], [ sag_020_f, "all", 0.01, 10 ], [ cc_020_m, "all", 0.01, 10 ], [ cc_020_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_cir ]
#    5_9 hcc:
#      adjustables: [[ i_sdis, "5-9M", 0.01, 10 ],[ i_edis, "5-9M", 0.01, 10 ],[ i_sdis, "5-9F", 0.01, 10 ],[ i_edis, "5-9F", 0.01, 10 ],[ i_hcp, "5-9M", 0.01, 10 ],[ i_ccp, "5-9F", 0.01, 10 ], [hcc_020_m, "all", 0.01, 10 ], [hcc_020_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_hcc ]
#
#    10_19 cirrhosis:
#      adjustables: [[ i_sdis, "10-19M", 0.01, 10 ],[ i_edis, "10-19M", 0.01, 10 ],[ i_sdis, "10-19F", 0.01, 10 ], [i_edis, "10-19F", 0.01, 10 ], [i_ccp, "10-19M", 0.01, 10 ],[ i_ccp, "10-19F", 0.01, 10 ],[ i_dcp, "10-19M", 0.01, 10 ],[ i_dcp, "10-19F", 0.01, 10 ],[ sag_020_m, "all", 0.01, 10 ], [ sag_020_f, "all", 0.01, 10 ], [ cc_020_m, "all", 0.01, 10 ], [ cc_020_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_cir ]
#    10_19 hcc:
#      adjustables: [[i_sdis, "10-19M", 0.01, 10 ],[ i_edis, "10-19M", 0.01, 10 ],[i_sdis, "10-19F", 0.01, 10 ], [i_edis, "10-19F", 0.01, 10 ],[ i_hcp, "10-19M", 0.01, 10 ],[ i_hcp, "10-19F", 0.1, 10 ], hcc_020_m, "all", 0.01, 10 ], [ hcc_020_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_hcc ]
#
#    20_29 cirrhosis:
#      adjustables: [[i_sdis, "20-29M", 0.01, 10 ],[ i_edis, "20-29M", 0.01, 10 ],[ i_sdis, "20-29F", 0.01, 10 ],[ i_edis, "20-29F", 0.01, 10 ],[i_ccp, "20-29M", 0.01, 10],[i_ccp, "20-29F", 0.01, 10],[i_dcp, "20-29M", 0.01, 10],[i_dcp, "20-29F", 0.01, 10], [ sag_2040_m, "all", 0.01, 10 ], [ sag_2040_f, "all", 0.01, 10 ], [ cc_2040_m, "all", 0.01, 10 ], [ cc_2040_f, "all", 0.01, 10 ]]
#      measurables: [ cl_cir ]
#    20_29 hcc:
#      adjustables: [[i_sdis, "20-29M", 0.01, 10 ],[ i_edis, "20-29M", 0.01, 10 ],[ i_sdis, "20-29F", 0.01, 10 ],[ i_edis, "20-29F", 0.01, 10 ],[i_hcp, "20-29M", 0.01, 10],[i_hcp, "20-29F", 0.01, 10], [ hcc_2040_m, "all", 0.01, 10 ], [ hcc_2040_f, "all", 0.01, 10 ]]
#      measurables: [ cl_hcc ]
#
#    30_39 cirrhosis:
#      adjustables: [[i_sdis, "30-39M", 0.01, 10 ],[ i_edis, "30-39M", 0.01, 10 ],[ i_sdis, "30-39F", 0.01, 10 ],[ i_edis, "30-39F", 0.01, 10 ],[ i_ccp, "30-39M", 0.01, 10 ],[ i_ccp, "30-39F", 0.01, 10 ], [ i_dcp, "30-39M", 0.01, 10 ],[ i_dcp, "30-39F", 0.01, 10 ], [ sag_2040_m, "all", 0.01, 10 ], [ sag_2040_f, "all", 0.01, 10 ], [ cc_2040_m, "all", 0.01, 10 ], [ cc_2040_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_cir ]
#    30_39 hcc:
#      adjustables: [[i_sdis, "30-39M", 0.01, 10 ],[ i_edis, "30-39M", 0.01, 10 ],[ i_sdis, "30-39F", 0.01, 10 ],[ i_edis, "30-39F", 0.01, 10 ],[ i_hcp, "30-39M", 0.01, 10 ],[ i_hcp, "30-39F", 0.01, 10 ], [hcc_2040_m, "all", 0.01, 10 ], [ hcc_2040_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_hcc ]
#
#    40_49 cirrhosis:
#      adjustables: [[i_sdis, "40-49M", 0.01, 10 ],[ i_edis, "40-49M", 0.01, 10 ],[ i_sdis, "40-49F", 0.01, 10 ],[ i_edis, "40-49F", 0.01, 10 ],[i_ccp, "40-49M", 0.01, 10],[i_ccp, "40-49F", 0.01, 10], [i_dcp, "40-49M", 0.01, 10],[i_dcp, "40-49F", 0.01, 10], [ sag_4060_m, "all", 0.01, 10 ], [ sag_4060_f, "all", 0.01, 10 ], [ cc_4060_m, "all", 0.01, 10 ], [ cc_4060_f, "all", 0.01, 10 ]]
#      measurables: [ cl_cir ]
#    40_49 hcc:
#      adjustables: [[i_sdis, "40-49M", 0.01, 10 ],[ i_edis, "40-49M", 0.01, 10 ],[ i_sdis, "40-49F", 0.01, 10 ],[ i_edis, "40-49F", 0.01, 10 ],[i_hcp, "40-49M", 0.01, 10],[i_hcp, "40-49F", 0.01, 10],[ hcc_4060_m, "all", 0.01, 10 ], [ hcc_4060_f, "all", 0.01, 10 ]]
#      measurables: [ cl_hcc ]
#
#    50_59 cirrhosis:
#      adjustables: [[i_sdis, "50-59M", 0.01, 10 ],[ i_edis, "50-59M", 0.01, 10 ],[ i_sdis, "50-59F", 0.01, 10 ],[ i_edis, "50-59F", 0.01, 10 ],[i_ccp, "50-59M", 0.01, 10],[i_ccp, "50-59F", 0.01, 10], [i_dcp, "50-59M", 0.01, 10],[i_dcp, "50-59F", 0.01, 10], [ sag_4060_m, "all", 0.01, 10 ], [ sag_4060_f, "all", 0.01, 10 ], [ cc_4060_m, "all", 0.01, 10 ], [ cc_4060_f, "all", 0.01, 10 ]]
#      measurables: [ cl_cir ]
#    50_59 hcc:
#      adjustables: [[i_sdis, "50-59M", 0.01, 10 ],[ i_edis, "50-59M", 0.01, 10 ],[ i_sdis, "50-59F", 0.01, 10 ],[ i_edis, "50-59F", 0.01, 10 ],[i_hcp, "50-59M", 0.01, 10],[i_hcp, "50-59F", 0.01, 10],[ hcc_4060_m, "all", 0.01, 10 ], [ hcc_4060_f, "all", 0.01, 10 ]]
#      measurables: [ cl_hcc ]
#
#    60_69 cirrhosis:
#      adjustables: [[i_sdis, "60-69M", 0.01, 10 ],[ i_edis, "60-69M", 0.01, 10 ],[ i_sdis, "60-69F", 0.01, 10 ],[ i_edis, "60-69F", 0.01, 10 ],[i_ccp, "60-69M", 0.01, 10],[i_ccp, "60-69F", 0.01, 10], [i_dcp, "60-69M", 0.01, 10],[i_dcp, "60-69F", 0.01, 10], [ sag_60_m, "all", 0.01, 10 ], [ sag_60_f, "all", 0.01, 10 ], [ cc_60_m, "all", 0.01, 10 ], [ cc_60_f, "all", 0.01, 10 ]]
#      measurables: [ cl_cir ]
#    60_69 hcc:
#      adjustables: [[i_sdis, "60-69M", 0.01, 10 ],[ i_edis, "60-69M", 0.01, 10 ],[ i_sdis, "60-69F", 0.01, 10 ],[ i_edis, "60-69F", 0.01, 10 ],[i_hcp, "60-69M", 0.01, 10],[i_hcp, "60-69F", 0.01, 10],[ hcc_60_m, "all", 0.01, 10 ], [ hcc_60_f, "all", 0.01, 10 ]]
#      measurables: [ cl_hcc ]
#
#    70_79 cirrhosis:
#      adjustables: [[i_sdis, "70-79M", 0.01, 10 ],[ i_edis, "70-79M", 0.01, 10 ],[ i_sdis, "70-79F", 0.01, 10 ],[ i_edis, "70-79F", 0.01, 10 ],[ i_ccp, "70-79M", 0.01, 10 ],[ i_ccp, "70-79F", 0.01, 10 ], [ i_dcp, "70-79M", 0.01, 10 ],[ i_dcp, "70-79F", 0.01, 10 ], [ sag_60_m, "all", 0.01, 10 ], [ sag_60_f, "all", 0.01, 10 ], [ cc_60_m, "all", 0.01, 10 ], [ cc_60_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_cir ]
#    70_79 hcc:
#      adjustables: [[i_sdis, "70-79M", 0.01, 10 ],[ i_edis, "70-79M", 0.01, 10 ],[ i_sdis, "70-79F", 0.01, 10 ],[ i_edis, "70-79F", 0.01, 10 ],[ i_hcp, "70-79M", 0.01, 10 ],[ i_hcp, "70-79F", 0.01, 10 ],[ hcc_60_m, "all", 0.01, 10 ], [ hcc_60_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_hcc ]
#
#    80_89 cirrhosis:
#      adjustables: [[i_sdis, "80-89M", 0.01, 10 ],[ i_edis, "80-89M", 0.01, 10 ],[ i_sdis, "80-89F", 0.01, 10 ],[ i_edis, "80-89F", 0.01, 10 ],[ i_ccp, "80-89M", 0.01, 10 ],[ i_ccp, "80-89F", 0.01, 10 ], [ i_dcp, "80-89M", 0.01, 10 ],[ i_dcp, "80-89F", 0.01, 10 ], [ sag_60_m, "all", 0.01, 10 ], [ sag_60_f, "all", 0.01, 10 ], [ cc_60_m, "all", 0.01, 10 ], [ cc_60_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_cir ]
#    80_89 hcc:
#      adjustables: [[i_sdis, "80-89M", 0.01, 10 ],[ i_edis, "80-89M", 0.01, 10 ],[ i_sdis, "80-89F", 0.01, 10 ],[ i_edis, "80-89F", 0.01, 10 ],[ i_hcp, "80-89M", 0.01, 10 ],[ i_hcp, "80-89F", 0.01, 10 ],[ hcc_60_m, "all", 0.01, 10 ], [ hcc_60_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_hcc ]
#
#    90+ cirrhosis:
#      adjustables: [ [i_sdis, "90+M", 0.01, 10 ],[ i_edis, "90+M", 0.01, 10 ],[ i_sdis, "90+F", 0.01, 10 ],[ i_edis, "90+F", 0.01, 10 ],[ i_ccp, "90+M", 0.01, 10 ],[ i_ccp, "90+F", 0.01, 10 ], [ i_dcp, "90+M", 0.01, 10 ],[ i_dcp, "90+F", 0.01, 10 ], [ sag_60_m, "all", 0.01, 10 ], [ sag_60_f, "all", 0.01, 10 ], [ cc_60_m, "all", 0.01, 10 ], [ cc_60_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_cir ]
#    90+ hcc:
#      adjustables: [ [i_sdis, "90+M", 0.01, 10 ],[ i_edis, "90+M", 0.01, 10 ],[ i_sdis, "90+F", 0.01, 10 ],[ i_edis, "90+F", 0.01, 10 ],[ i_hcp, "90+M", 0.01, 10 ],[ i_hcp, "90+F", 0.01, 10 ], [ hcc_60_m, "all", 0.01, 10 ], [ hcc_60_f, "all", 0.01, 10 ] ]
#      measurables: [ cl_hcc ]


## ALL AGE BINS NO INITIAL CONDITIONS
    0_0 cirrhosis:
      adjustables: [ [ sag_020_m, "all", 0.01, 10 ], [ sag_020_f, "all", 0.01, 10 ], [ cc_020_m, "all", 0.01, 10 ], [ cc_020_f, "all", 0.01, 10 ] ]
      measurables: [ cl_cir ]
    0_0 hcc:
      adjustables: [ [hcc_020_m, "all", 0.01, 10 ], [ hcc_020_f, "all", 0.01, 10 ] ]
      measurables: [ cl_hcc ]

    1_4 cirrhosis:
      adjustables: [ [ sag_020_m, "all", 0.01, 10 ], [ sag_020_f, "all", 0.01, 10 ], [ cc_020_m, "all", 0.01, 10 ], [ cc_020_f, "all", 0.01, 10 ] ]
      measurables: [ cl_cir ]
    1_4 hcc:
      adjustables: [ [hcc_020_m, "all", 0.01, 10 ], [ hcc_020_f, "all", 0.01, 10 ] ]
      measurables: [ cl_hcc ]

    5_9 cirrhosis:
      adjustables: [ [ sag_020_m, "all", 0.01, 10 ], [ sag_020_f, "all", 0.01, 10 ], [ cc_020_m, "all", 0.01, 10 ], [ cc_020_f, "all", 0.01, 10 ] ]
      measurables: [ cl_cir ]
    5_9 hcc:
      adjustables: [ [hcc_020_m, "all", 0.01, 10 ], [hcc_020_f, "all", 0.01, 10 ] ]
      measurables: [ cl_hcc ]

    10_19 cirrhosis:
      adjustables: [ [ sag_020_m, "all", 0.01, 10 ], [ sag_020_f, "all", 0.01, 10 ], [ cc_020_m, "all", 0.01, 10 ], [ cc_020_f, "all", 0.01, 10 ] ]
      measurables: [ cl_cir ]
    10_19 hcc:
      adjustables: [ [hcc_020_m, "all", 0.01, 10 ], [ hcc_020_f, "all", 0.01, 10 ] ]
      measurables: [ cl_hcc ]

    20_29 cirrhosis:
      adjustables: [ [ sag_2040_m, "all", 0.01, 10 ], [ sag_2040_f, "all", 0.01, 10 ], [ cc_2040_m, "all", 0.01, 10 ], [ cc_2040_f, "all", 0.01, 10 ]]
      measurables: [ cl_cir ]
    20_29 hcc:
      adjustables: [ [ hcc_2040_m, "all", 0.01, 10 ], [ hcc_2040_f, "all", 0.01, 10 ]]
      measurables: [ cl_hcc ]

    30_39 cirrhosis:
      adjustables: [ [ sag_2040_m, "all", 0.01, 10 ], [ sag_2040_f, "all", 0.01, 10 ], [ cc_2040_m, "all", 0.01, 10 ], [ cc_2040_f, "all", 0.01, 10 ] ]
      measurables: [ cl_cir ]
    30_39 hcc:
      adjustables: [ [hcc_2040_m, "all", 0.01, 10 ], [ hcc_2040_f, "all", 0.01, 10 ] ]
      measurables: [ cl_hcc ]

    40_49 cirrhosis:
      adjustables: [ [ sag_4060_m, "all", 0.01, 10 ], [ sag_4060_f, "all", 0.01, 10 ], [ cc_4060_m, "all", 0.01, 10 ], [ cc_4060_f, "all", 0.01, 10 ]]
      measurables: [ cl_cir ]
    40_49 hcc:
      adjustables: [[ hcc_4060_m, "all", 0.01, 10 ], [ hcc_4060_f, "all", 0.01, 10 ]]
      measurables: [ cl_hcc ]

    50_59 cirrhosis:
      adjustables: [[ sag_4060_m, "all", 0.01, 10 ], [ sag_4060_f, "all", 0.01, 10 ], [ cc_4060_m, "all", 0.01, 10 ], [ cc_4060_f, "all", 0.01, 10 ]]
      measurables: [ cl_cir ]
    50_59 hcc:
      adjustables: [[ hcc_4060_m, "all", 0.01, 10 ], [ hcc_4060_f, "all", 0.01, 10 ]]
      measurables: [ cl_hcc ]

    60_69 cirrhosis:
      adjustables: [ [ sag_60_m, "all", 0.01, 10 ], [ sag_60_f, "all", 0.01, 10 ], [ cc_60_m, "all", 0.01, 10 ], [ cc_60_f, "all", 0.01, 10 ]]
      measurables: [ cl_cir ]
    60_69 hcc:
      adjustables: [[ hcc_60_m, "all", 0.01, 10 ], [ hcc_60_f, "all", 0.01, 10 ]]
      measurables: [ cl_hcc ]

    70_79 cirrhosis:
      adjustables: [ [ sag_60_m, "all", 0.01, 10 ], [ sag_60_f, "all", 0.01, 10 ], [ cc_60_m, "all", 0.01, 10 ], [ cc_60_f, "all", 0.01, 10 ] ]
      measurables: [ cl_cir ]
    70_79 hcc:
      adjustables: [ [ hcc_60_m, "all", 0.01, 10 ], [ hcc_60_f, "all", 0.01, 10 ] ]
      measurables: [ cl_hcc ]

    80_89 cirrhosis:
      adjustables: [ [ sag_60_m, "all", 0.01, 10 ], [ sag_60_f, "all", 0.01, 10 ], [ cc_60_m, "all", 0.01, 10 ], [ cc_60_f, "all", 0.01, 10 ] ]
      measurables: [ cl_cir ]
    80_89 hcc:
      adjustables: [ [ hcc_60_m, "all", 0.01, 10 ], [ hcc_60_f, "all", 0.01, 10 ] ]
      measurables: [ cl_hcc ]

    90+ cirrhosis:
      adjustables: [ [ sag_60_m, "all", 0.01, 10 ], [ sag_60_f, "all", 0.01, 10 ], [ cc_60_m, "all", 0.01, 10 ], [ cc_60_f, "all", 0.01, 10 ] ]
      measurables: [ cl_cir ]
    90+ hcc:
      adjustables: [ [ hcc_60_m, "all", 0.01, 10 ], [ hcc_60_f, "all", 0.01, 10 ] ]
      measurables: [ cl_hcc ]

